server:
  port: 8762
spring:
  application:
    name: blog-service
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    serviceUrl:
      defaultZone: http://server-service:8761/eureka/
