server:
# 更改端口，启动多个service，server可注册多个实例，相当于多个集群
  port: 8763

spring:
  application:
  # 服务与服务之间相互调用一般都是根据这个name
    name: service-hello

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
