eureka:
  client:
    serviceUrl:
      defaultZone: http://server-service:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: zuul-service
zuul:
  routes:
    api-a:
      path: /blog-api/**
      serviceId: blog-service
    api-b:
      path: /video-api/**
      serviceId: video-service


